export const COMMON_INSTRUMENTS = [
  'Guitar',
  'Bass',
  'Drums',
  'Vocals',
  'Piano',
  'Keyboard',
  'Saxophone',
  'Trumpet',
  'Violin',
  'Cello',
  'Flute',
  'Harmonica',
  'Ukulele',
  'Banjo',
  'Mandolin',
  'Accordion',
  'DJ/Turntables',
  'Electronic/Production',
  'Percussion',
  'Trombone',
  'Clarinet',
  'Double Bass',
  'Harp',
  'Organ',
]

export const MUSIC_GENRES = [
  'Rock',
  'Pop',
  'Jazz',
  'Blues',
  'Metal',
  'Country',
  'Folk',
  'R&B',
  'Hip Hop',
  'Electronic',
  'Classical',
  'Indie',
  'Alternative',
  'Punk',
  'Reggae',
  'Funk',
  'Soul',
  'Latin',
  'World',
  'Experimental',
  'Ambient',
  'House',
  'Techno',
  'Dubstep',
  'Trap',
  'Gospel',
  'Bluegrass',
  'Ska',
  'Progressive',
  'Psychedelic',
]

export const LOOKING_FOR_OPTIONS = [
  'Band to Join',
  'Musicians for My Band',
  'Jam Sessions',
  'Recording Projects',
  'Live Performance',
  'Songwriting Partner',
  'Producer',
  'Teaching/Lessons',
  'Session Work',
  'Tour Opportunities',
  'Music Collaboration',
  'Open Mic Partners',
  'Studio Time',
  'Music Video Projects',
  'Networking',
]

export const BAND_ROLES = [
  'Lead Guitar',
  'Rhythm Guitar', 
  'Bass Player',
  'Drummer',
  'Lead Vocals',
  'Backing Vocals',
  'Keyboardist',
  'Pianist',
  'Saxophonist',
  'Trumpeter',
  'Violinist',
  'Cellist',
  'Flutist',
  'Harmonica Player',
  'DJ',
  'Producer',
  'Sound Engineer',
  'Percussionist',
  'Accordion Player',
  'Banjo Player',
  'Mandolin Player',
  'Ukulele Player',
  'Violin',
  'Cello',
  'Guitar',
  'Bass',
  'Drums',
  'Vocals',
  'Keyboard',
  'Piano',
  'Saxophone',
  'Trumpet'
]

export const EXPERIENCE_LEVELS = [
  { value: 'Beginner', label: 'Beginner', description: 'Just starting out, learning the basics' },
  { value: 'Intermediate', label: 'Intermediate', description: 'Comfortable playing, some performance experience' },
  { value: 'Advanced', label: 'Advanced', description: 'Highly skilled, extensive performance experience' },
  { value: 'Professional', label: 'Professional', description: 'Making a living from music' },
]