// Zip code to city/state lookup using Zippopotam.us API
// This provides comprehensive coverage of all US zip codes

interface LocationInfo {
  city: string
  state: string
}

// Cache for API results to avoid repeated calls
const locationCache = new Map<string, LocationInfo | null>()

/**
 * Fetches location data from Zippopotam.us API
 * @param zipCode - 5-digit US zip code
 * @returns LocationInfo object with city and state, or null if not found
 */
async function fetchLocationFromAPI(zipCode: string): Promise<LocationInfo | null> {
  try {
    const response = await fetch(`https://api.zippopotam.us/us/${zipCode}`)
    
    if (!response.ok) {
      return null
    }
    
    const data = await response.json()
    
    if (data.places && data.places.length > 0) {
      const place = data.places[0]
      return {
        city: place['place name'],
        state: place['state abbreviation']
      }
    }
    
    return null
  } catch (error) {
    console.warn('Failed to fetch location for zip code:', zipCode, error)
    return null
  }
}

// Basic fallback lookup for offline/error cases - just major cities
const FALLBACK_ZIP_TO_LOCATION: Record<string, LocationInfo> = {
  // New York
  '10001': { city: 'New York', state: 'NY' },
  '10006': { city: 'New York', state: 'NY' },
  '10007': { city: 'New York', state: 'NY' },
  '10008': { city: 'New York', state: 'NY' },
  '10009': { city: 'New York', state: 'NY' },
  '10010': { city: 'New York', state: 'NY' },
  '10011': { city: 'New York', state: 'NY' },
  '10012': { city: 'New York', state: 'NY' },
  '10013': { city: 'New York', state: 'NY' },
  '10014': { city: 'New York', state: 'NY' },
  '10015': { city: 'New York', state: 'NY' },
  '10016': { city: 'New York', state: 'NY' },
  '10017': { city: 'New York', state: 'NY' },
  '10018': { city: 'New York', state: 'NY' },
  '10019': { city: 'New York', state: 'NY' },
  '10020': { city: 'New York', state: 'NY' },
  '10021': { city: 'New York', state: 'NY' },
  '10022': { city: 'New York', state: 'NY' },
  '10023': { city: 'New York', state: 'NY' },
  '10024': { city: 'New York', state: 'NY' },
  '10025': { city: 'New York', state: 'NY' },
  '10026': { city: 'New York', state: 'NY' },
  '10027': { city: 'New York', state: 'NY' },
  '10028': { city: 'New York', state: 'NY' },
  '10029': { city: 'New York', state: 'NY' },
  '10030': { city: 'New York', state: 'NY' },
  
  // Los Angeles
  '90001': { city: 'Los Angeles', state: 'CA' },
  '90002': { city: 'Los Angeles', state: 'CA' },
  '90003': { city: 'Los Angeles', state: 'CA' },
  '90004': { city: 'Los Angeles', state: 'CA' },
  '90005': { city: 'Los Angeles', state: 'CA' },
  '90006': { city: 'Los Angeles', state: 'CA' },
  '90007': { city: 'Los Angeles', state: 'CA' },
  '90008': { city: 'Los Angeles', state: 'CA' },
  '90009': { city: 'Los Angeles', state: 'CA' },
  '90010': { city: 'Los Angeles', state: 'CA' },
  '90011': { city: 'Los Angeles', state: 'CA' },
  '90012': { city: 'Los Angeles', state: 'CA' },
  '90013': { city: 'Los Angeles', state: 'CA' },
  '90014': { city: 'Los Angeles', state: 'CA' },
  '90015': { city: 'Los Angeles', state: 'CA' },
  '90016': { city: 'Los Angeles', state: 'CA' },
  '90017': { city: 'Los Angeles', state: 'CA' },
  '90018': { city: 'Los Angeles', state: 'CA' },
  '90019': { city: 'Los Angeles', state: 'CA' },
  '90020': { city: 'Los Angeles', state: 'CA' },
  '90021': { city: 'Los Angeles', state: 'CA' },
  '90022': { city: 'Los Angeles', state: 'CA' },
  '90023': { city: 'Los Angeles', state: 'CA' },
  '90024': { city: 'Los Angeles', state: 'CA' },
  '90025': { city: 'Los Angeles', state: 'CA' },
  '90026': { city: 'Los Angeles', state: 'CA' },
  '90027': { city: 'Los Angeles', state: 'CA' },
  '90028': { city: 'Los Angeles', state: 'CA' },
  '90029': { city: 'Los Angeles', state: 'CA' },
  '90030': { city: 'Los Angeles', state: 'CA' },
  
  // Chicago
  '60601': { city: 'Chicago', state: 'IL' },
  '60602': { city: 'Chicago', state: 'IL' },
  '60603': { city: 'Chicago', state: 'IL' },
  '60604': { city: 'Chicago', state: 'IL' },
  '60605': { city: 'Chicago', state: 'IL' },
  '60606': { city: 'Chicago', state: 'IL' },
  '60607': { city: 'Chicago', state: 'IL' },
  '60608': { city: 'Chicago', state: 'IL' },
  '60609': { city: 'Chicago', state: 'IL' },
  '60610': { city: 'Chicago', state: 'IL' },
  '60611': { city: 'Chicago', state: 'IL' },
  '60612': { city: 'Chicago', state: 'IL' },
  '60613': { city: 'Chicago', state: 'IL' },
  '60614': { city: 'Chicago', state: 'IL' },
  '60615': { city: 'Chicago', state: 'IL' },
  '60616': { city: 'Chicago', state: 'IL' },
  '60617': { city: 'Chicago', state: 'IL' },
  '60618': { city: 'Chicago', state: 'IL' },
  '60619': { city: 'Chicago', state: 'IL' },
  '60620': { city: 'Chicago', state: 'IL' },
  '60621': { city: 'Chicago', state: 'IL' },
  '60622': { city: 'Chicago', state: 'IL' },
  '60623': { city: 'Chicago', state: 'IL' },
  '60624': { city: 'Chicago', state: 'IL' },
  '60625': { city: 'Chicago', state: 'IL' },
  '60626': { city: 'Chicago', state: 'IL' },
  '60627': { city: 'Chicago', state: 'IL' },
  '60628': { city: 'Chicago', state: 'IL' },
  '60629': { city: 'Chicago', state: 'IL' },
  '60630': { city: 'Chicago', state: 'IL' },
  
  // Houston
  '77001': { city: 'Houston', state: 'TX' },
  '77002': { city: 'Houston', state: 'TX' },
  '77003': { city: 'Houston', state: 'TX' },
  '77004': { city: 'Houston', state: 'TX' },
  '77005': { city: 'Houston', state: 'TX' },
  '77006': { city: 'Houston', state: 'TX' },
  '77007': { city: 'Houston', state: 'TX' },
  '77008': { city: 'Houston', state: 'TX' },
  '77009': { city: 'Houston', state: 'TX' },
  '77010': { city: 'Houston', state: 'TX' },
  '77011': { city: 'Houston', state: 'TX' },
  '77012': { city: 'Houston', state: 'TX' },
  '77013': { city: 'Houston', state: 'TX' },
  '77014': { city: 'Houston', state: 'TX' },
  '77015': { city: 'Houston', state: 'TX' },
  '77016': { city: 'Houston', state: 'TX' },
  '77017': { city: 'Houston', state: 'TX' },
  '77018': { city: 'Houston', state: 'TX' },
  '77019': { city: 'Houston', state: 'TX' },
  '77020': { city: 'Houston', state: 'TX' },
  '77021': { city: 'Houston', state: 'TX' },
  '77022': { city: 'Houston', state: 'TX' },
  '77023': { city: 'Houston', state: 'TX' },
  '77024': { city: 'Houston', state: 'TX' },
  '77025': { city: 'Houston', state: 'TX' },
  '77026': { city: 'Houston', state: 'TX' },
  '77027': { city: 'Houston', state: 'TX' },
  '77028': { city: 'Houston', state: 'TX' },
  '77029': { city: 'Houston', state: 'TX' },
  '77030': { city: 'Houston', state: 'TX' },
  
  // Phoenix
  '85001': { city: 'Phoenix', state: 'AZ' },
  '85002': { city: 'Phoenix', state: 'AZ' },
  '85003': { city: 'Phoenix', state: 'AZ' },
  '85004': { city: 'Phoenix', state: 'AZ' },
  '85005': { city: 'Phoenix', state: 'AZ' },
  '85006': { city: 'Phoenix', state: 'AZ' },
  '85007': { city: 'Phoenix', state: 'AZ' },
  '85008': { city: 'Phoenix', state: 'AZ' },
  '85009': { city: 'Phoenix', state: 'AZ' },
  '85010': { city: 'Phoenix', state: 'AZ' },
  '85011': { city: 'Phoenix', state: 'AZ' },
  '85012': { city: 'Phoenix', state: 'AZ' },
  '85013': { city: 'Phoenix', state: 'AZ' },
  '85014': { city: 'Phoenix', state: 'AZ' },
  '85015': { city: 'Phoenix', state: 'AZ' },
  '85016': { city: 'Phoenix', state: 'AZ' },
  '85017': { city: 'Phoenix', state: 'AZ' },
  '85018': { city: 'Phoenix', state: 'AZ' },
  '85019': { city: 'Phoenix', state: 'AZ' },
  '85020': { city: 'Phoenix', state: 'AZ' },
  '85021': { city: 'Phoenix', state: 'AZ' },
  '85022': { city: 'Phoenix', state: 'AZ' },
  '85023': { city: 'Phoenix', state: 'AZ' },
  '85024': { city: 'Phoenix', state: 'AZ' },
  '85025': { city: 'Phoenix', state: 'AZ' },
  '85026': { city: 'Phoenix', state: 'AZ' },
  '85027': { city: 'Phoenix', state: 'AZ' },
  '85028': { city: 'Phoenix', state: 'AZ' },
  '85029': { city: 'Phoenix', state: 'AZ' },
  '85030': { city: 'Phoenix', state: 'AZ' },
  
  // Philadelphia  
  '19101': { city: 'Philadelphia', state: 'PA' },
  '19102': { city: 'Philadelphia', state: 'PA' },
  '19103': { city: 'Philadelphia', state: 'PA' },
  '19104': { city: 'Philadelphia', state: 'PA' },
  '19105': { city: 'Philadelphia', state: 'PA' },
  '19106': { city: 'Philadelphia', state: 'PA' },
  '19107': { city: 'Philadelphia', state: 'PA' },
  '19108': { city: 'Philadelphia', state: 'PA' },
  '19109': { city: 'Philadelphia', state: 'PA' },
  '19110': { city: 'Philadelphia', state: 'PA' },
  '19111': { city: 'Philadelphia', state: 'PA' },
  '19112': { city: 'Philadelphia', state: 'PA' },
  '19113': { city: 'Philadelphia', state: 'PA' },
  '19114': { city: 'Philadelphia', state: 'PA' },
  '19115': { city: 'Philadelphia', state: 'PA' },
  '19116': { city: 'Philadelphia', state: 'PA' },
  '19117': { city: 'Philadelphia', state: 'PA' },
  '19118': { city: 'Philadelphia', state: 'PA' },
  '19119': { city: 'Philadelphia', state: 'PA' },
  '19120': { city: 'Philadelphia', state: 'PA' },
  '19121': { city: 'Philadelphia', state: 'PA' },
  '19122': { city: 'Philadelphia', state: 'PA' },
  '19123': { city: 'Philadelphia', state: 'PA' },
  '19124': { city: 'Philadelphia', state: 'PA' },
  '19125': { city: 'Philadelphia', state: 'PA' },
  '19126': { city: 'Philadelphia', state: 'PA' },
  '19127': { city: 'Philadelphia', state: 'PA' },
  '19128': { city: 'Philadelphia', state: 'PA' },
  '19129': { city: 'Philadelphia', state: 'PA' },
  '19130': { city: 'Philadelphia', state: 'PA' },
  
  // San Antonio
  '78201': { city: 'San Antonio', state: 'TX' },
  '78202': { city: 'San Antonio', state: 'TX' },
  '78203': { city: 'San Antonio', state: 'TX' },
  '78204': { city: 'San Antonio', state: 'TX' },
  '78205': { city: 'San Antonio', state: 'TX' },
  '78206': { city: 'San Antonio', state: 'TX' },
  '78207': { city: 'San Antonio', state: 'TX' },
  '78208': { city: 'San Antonio', state: 'TX' },
  '78209': { city: 'San Antonio', state: 'TX' },
  '78210': { city: 'San Antonio', state: 'TX' },
  '78211': { city: 'San Antonio', state: 'TX' },
  '78212': { city: 'San Antonio', state: 'TX' },
  '78213': { city: 'San Antonio', state: 'TX' },
  '78214': { city: 'San Antonio', state: 'TX' },
  '78215': { city: 'San Antonio', state: 'TX' },
  '78216': { city: 'San Antonio', state: 'TX' },
  '78217': { city: 'San Antonio', state: 'TX' },
  '78218': { city: 'San Antonio', state: 'TX' },
  '78219': { city: 'San Antonio', state: 'TX' },
  '78220': { city: 'San Antonio', state: 'TX' },
  '78221': { city: 'San Antonio', state: 'TX' },
  '78222': { city: 'San Antonio', state: 'TX' },
  '78223': { city: 'San Antonio', state: 'TX' },
  '78224': { city: 'San Antonio', state: 'TX' },
  '78225': { city: 'San Antonio', state: 'TX' },
  '78226': { city: 'San Antonio', state: 'TX' },
  '78227': { city: 'San Antonio', state: 'TX' },
  '78228': { city: 'San Antonio', state: 'TX' },
  '78229': { city: 'San Antonio', state: 'TX' },
  '78230': { city: 'San Antonio', state: 'TX' },
  
  // San Diego
  '92101': { city: 'San Diego', state: 'CA' },
  '92102': { city: 'San Diego', state: 'CA' },
  '92103': { city: 'San Diego', state: 'CA' },
  '92104': { city: 'San Diego', state: 'CA' },
  '92105': { city: 'San Diego', state: 'CA' },
  '92106': { city: 'San Diego', state: 'CA' },
  '92107': { city: 'San Diego', state: 'CA' },
  '92108': { city: 'San Diego', state: 'CA' },
  '92109': { city: 'San Diego', state: 'CA' },
  '92110': { city: 'San Diego', state: 'CA' },
  '92111': { city: 'San Diego', state: 'CA' },
  '92112': { city: 'San Diego', state: 'CA' },
  '92113': { city: 'San Diego', state: 'CA' },
  '92114': { city: 'San Diego', state: 'CA' },
  '92115': { city: 'San Diego', state: 'CA' },
  '92116': { city: 'San Diego', state: 'CA' },
  '92117': { city: 'San Diego', state: 'CA' },
  '92118': { city: 'San Diego', state: 'CA' },
  '92119': { city: 'San Diego', state: 'CA' },
  '92120': { city: 'San Diego', state: 'CA' },
  '92121': { city: 'San Diego', state: 'CA' },
  '92122': { city: 'San Diego', state: 'CA' },
  '92123': { city: 'San Diego', state: 'CA' },
  '92124': { city: 'San Diego', state: 'CA' },
  '92125': { city: 'San Diego', state: 'CA' },
  '92126': { city: 'San Diego', state: 'CA' },
  '92127': { city: 'San Diego', state: 'CA' },
  '92128': { city: 'San Diego', state: 'CA' },
  '92129': { city: 'San Diego', state: 'CA' },
  '92130': { city: 'San Diego', state: 'CA' },
  
  // Dallas
  '75201': { city: 'Dallas', state: 'TX' },
  '75202': { city: 'Dallas', state: 'TX' },
  '75203': { city: 'Dallas', state: 'TX' },
  '75204': { city: 'Dallas', state: 'TX' },
  '75205': { city: 'Dallas', state: 'TX' },
  '75206': { city: 'Dallas', state: 'TX' },
  '75207': { city: 'Dallas', state: 'TX' },
  '75208': { city: 'Dallas', state: 'TX' },
  '75209': { city: 'Dallas', state: 'TX' },
  '75210': { city: 'Dallas', state: 'TX' },
  '75211': { city: 'Dallas', state: 'TX' },
  '75212': { city: 'Dallas', state: 'TX' },
  '75213': { city: 'Dallas', state: 'TX' },
  '75214': { city: 'Dallas', state: 'TX' },
  '75215': { city: 'Dallas', state: 'TX' },
  '75216': { city: 'Dallas', state: 'TX' },
  '75217': { city: 'Dallas', state: 'TX' },
  '75218': { city: 'Dallas', state: 'TX' },
  '75219': { city: 'Dallas', state: 'TX' },
  '75220': { city: 'Dallas', state: 'TX' },
  '75221': { city: 'Dallas', state: 'TX' },
  '75222': { city: 'Dallas', state: 'TX' },
  '75223': { city: 'Dallas', state: 'TX' },
  '75224': { city: 'Dallas', state: 'TX' },
  '75225': { city: 'Dallas', state: 'TX' },
  '75226': { city: 'Dallas', state: 'TX' },
  '75227': { city: 'Dallas', state: 'TX' },
  '75228': { city: 'Dallas', state: 'TX' },
  '75229': { city: 'Dallas', state: 'TX' },
  '75230': { city: 'Dallas', state: 'TX' },
  
  // San Jose
  '95101': { city: 'San Jose', state: 'CA' },
  '95102': { city: 'San Jose', state: 'CA' },
  '95103': { city: 'San Jose', state: 'CA' },
  '95104': { city: 'San Jose', state: 'CA' },
  '95105': { city: 'San Jose', state: 'CA' },
  '95106': { city: 'San Jose', state: 'CA' },
  '95107': { city: 'San Jose', state: 'CA' },
  '95108': { city: 'San Jose', state: 'CA' },
  '95109': { city: 'San Jose', state: 'CA' },
  '95110': { city: 'San Jose', state: 'CA' },
  '95111': { city: 'San Jose', state: 'CA' },
  '95112': { city: 'San Jose', state: 'CA' },
  '95113': { city: 'San Jose', state: 'CA' },
  '95114': { city: 'San Jose', state: 'CA' },
  '95115': { city: 'San Jose', state: 'CA' },
  '95116': { city: 'San Jose', state: 'CA' },
  '95117': { city: 'San Jose', state: 'CA' },
  '95118': { city: 'San Jose', state: 'CA' },
  '95119': { city: 'San Jose', state: 'CA' },
  '95120': { city: 'San Jose', state: 'CA' },
  '95121': { city: 'San Jose', state: 'CA' },
  '95122': { city: 'San Jose', state: 'CA' },
  '95123': { city: 'San Jose', state: 'CA' },
  '95124': { city: 'San Jose', state: 'CA' },
  '95125': { city: 'San Jose', state: 'CA' },
  '95126': { city: 'San Jose', state: 'CA' },
  '95127': { city: 'San Jose', state: 'CA' },
  '95128': { city: 'San Jose', state: 'CA' },
  '95129': { city: 'San Jose', state: 'CA' },
  '95130': { city: 'San Jose', state: 'CA' },
  
  // More NYC boroughs and suburbs
  '10031': { city: 'New York', state: 'NY' },
  '10032': { city: 'New York', state: 'NY' },
  '10033': { city: 'New York', state: 'NY' },
  '10034': { city: 'New York', state: 'NY' },
  '10035': { city: 'New York', state: 'NY' },
  '10036': { city: 'New York', state: 'NY' },
  '10037': { city: 'New York', state: 'NY' },
  '10038': { city: 'New York', state: 'NY' },
  '10039': { city: 'New York', state: 'NY' },
  '10040': { city: 'New York', state: 'NY' },
  '10041': { city: 'New York', state: 'NY' },
  '10043': { city: 'New York', state: 'NY' },
  '10044': { city: 'New York', state: 'NY' },
  '10045': { city: 'New York', state: 'NY' },
  '10055': { city: 'New York', state: 'NY' },
  '10060': { city: 'New York', state: 'NY' },
  '10065': { city: 'New York', state: 'NY' },
  '10069': { city: 'New York', state: 'NY' },
  '10075': { city: 'New York', state: 'NY' },
  '10128': { city: 'New York', state: 'NY' },
  '10280': { city: 'New York', state: 'NY' },
  '10282': { city: 'New York', state: 'NY' },
  
  // Brooklyn
  '11201': { city: 'Brooklyn', state: 'NY' },
  '11202': { city: 'Brooklyn', state: 'NY' },
  '11203': { city: 'Brooklyn', state: 'NY' },
  '11204': { city: 'Brooklyn', state: 'NY' },
  '11205': { city: 'Brooklyn', state: 'NY' },
  '11206': { city: 'Brooklyn', state: 'NY' },
  '11207': { city: 'Brooklyn', state: 'NY' },
  '11208': { city: 'Brooklyn', state: 'NY' },
  '11209': { city: 'Brooklyn', state: 'NY' },
  '11210': { city: 'Brooklyn', state: 'NY' },
  '11211': { city: 'Brooklyn', state: 'NY' },
  '11212': { city: 'Brooklyn', state: 'NY' },
  '11213': { city: 'Brooklyn', state: 'NY' },
  '11214': { city: 'Brooklyn', state: 'NY' },
  '11215': { city: 'Brooklyn', state: 'NY' },
  '11216': { city: 'Brooklyn', state: 'NY' },
  '11217': { city: 'Brooklyn', state: 'NY' },
  '11218': { city: 'Brooklyn', state: 'NY' },
  '11219': { city: 'Brooklyn', state: 'NY' },
  '11220': { city: 'Brooklyn', state: 'NY' },
  '11221': { city: 'Brooklyn', state: 'NY' },
  '11222': { city: 'Brooklyn', state: 'NY' },
  '11223': { city: 'Brooklyn', state: 'NY' },
  '11224': { city: 'Brooklyn', state: 'NY' },
  '11225': { city: 'Brooklyn', state: 'NY' },
  '11226': { city: 'Brooklyn', state: 'NY' },
  '11228': { city: 'Brooklyn', state: 'NY' },
  '11229': { city: 'Brooklyn', state: 'NY' },
  '11230': { city: 'Brooklyn', state: 'NY' },
  '11231': { city: 'Brooklyn', state: 'NY' },
  '11232': { city: 'Brooklyn', state: 'NY' },
  '11233': { city: 'Brooklyn', state: 'NY' },
  '11234': { city: 'Brooklyn', state: 'NY' },
  '11235': { city: 'Brooklyn', state: 'NY' },
  '11236': { city: 'Brooklyn', state: 'NY' },
  '11237': { city: 'Brooklyn', state: 'NY' },
  '11238': { city: 'Brooklyn', state: 'NY' },
  '11239': { city: 'Brooklyn', state: 'NY' },
  
  // Queens
  '11101': { city: 'Queens', state: 'NY' },
  '11102': { city: 'Queens', state: 'NY' },
  '11103': { city: 'Queens', state: 'NY' },
  '11104': { city: 'Queens', state: 'NY' },
  '11105': { city: 'Queens', state: 'NY' },
  '11106': { city: 'Queens', state: 'NY' },
  '11109': { city: 'Queens', state: 'NY' },
  '11354': { city: 'Queens', state: 'NY' },
  '11355': { city: 'Queens', state: 'NY' },
  '11356': { city: 'Queens', state: 'NY' },
  '11357': { city: 'Queens', state: 'NY' },
  '11358': { city: 'Queens', state: 'NY' },
  '11359': { city: 'Queens', state: 'NY' },
  '11360': { city: 'Queens', state: 'NY' },
  '11361': { city: 'Queens', state: 'NY' },
  '11362': { city: 'Queens', state: 'NY' },
  '11363': { city: 'Queens', state: 'NY' },
  '11364': { city: 'Queens', state: 'NY' },
  '11365': { city: 'Queens', state: 'NY' },
  '11366': { city: 'Queens', state: 'NY' },
  '11367': { city: 'Queens', state: 'NY' },
  '11368': { city: 'Queens', state: 'NY' },
  '11369': { city: 'Queens', state: 'NY' },
  '11370': { city: 'Queens', state: 'NY' },
  '11371': { city: 'Queens', state: 'NY' },
  '11372': { city: 'Queens', state: 'NY' },
  '11373': { city: 'Queens', state: 'NY' },
  '11374': { city: 'Queens', state: 'NY' },
  '11375': { city: 'Queens', state: 'NY' },
  '11377': { city: 'Queens', state: 'NY' },
  '11378': { city: 'Queens', state: 'NY' },
  '11379': { city: 'Queens', state: 'NY' },
  '11385': { city: 'Queens', state: 'NY' },
  
  // Bronx
  '10451': { city: 'Bronx', state: 'NY' },
  '10452': { city: 'Bronx', state: 'NY' },
  '10453': { city: 'Bronx', state: 'NY' },
  '10454': { city: 'Bronx', state: 'NY' },
  '10455': { city: 'Bronx', state: 'NY' },
  '10456': { city: 'Bronx', state: 'NY' },
  '10457': { city: 'Bronx', state: 'NY' },
  '10458': { city: 'Bronx', state: 'NY' },
  '10459': { city: 'Bronx', state: 'NY' },
  '10460': { city: 'Bronx', state: 'NY' },
  '10461': { city: 'Bronx', state: 'NY' },
  '10462': { city: 'Bronx', state: 'NY' },
  '10463': { city: 'Bronx', state: 'NY' },
  '10464': { city: 'Bronx', state: 'NY' },
  '10465': { city: 'Bronx', state: 'NY' },
  '10466': { city: 'Bronx', state: 'NY' },
  '10467': { city: 'Bronx', state: 'NY' },
  '10468': { city: 'Bronx', state: 'NY' },
  '10469': { city: 'Bronx', state: 'NY' },
  '10470': { city: 'Bronx', state: 'NY' },
  '10471': { city: 'Bronx', state: 'NY' },
  '10472': { city: 'Bronx', state: 'NY' },
  '10473': { city: 'Bronx', state: 'NY' },
  '10474': { city: 'Bronx', state: 'NY' },
  '10475': { city: 'Bronx', state: 'NY' },
  
  // Staten Island
  '10301': { city: 'Staten Island', state: 'NY' },
  '10302': { city: 'Staten Island', state: 'NY' },
  '10303': { city: 'Staten Island', state: 'NY' },
  '10304': { city: 'Staten Island', state: 'NY' },
  '10305': { city: 'Staten Island', state: 'NY' },
  '10306': { city: 'Staten Island', state: 'NY' },
  '10307': { city: 'Staten Island', state: 'NY' },
  '10308': { city: 'Staten Island', state: 'NY' },
  '10309': { city: 'Staten Island', state: 'NY' },
  '10310': { city: 'Staten Island', state: 'NY' },
  '10311': { city: 'Staten Island', state: 'NY' },
  '10312': { city: 'Staten Island', state: 'NY' },
  '10313': { city: 'Staten Island', state: 'NY' },
  '10314': { city: 'Staten Island', state: 'NY' },
  
  // More California cities
  '90031': { city: 'Los Angeles', state: 'CA' },
  '90032': { city: 'Los Angeles', state: 'CA' },
  '90033': { city: 'Los Angeles', state: 'CA' },
  '90034': { city: 'Los Angeles', state: 'CA' },
  '90035': { city: 'Los Angeles', state: 'CA' },
  '90036': { city: 'Los Angeles', state: 'CA' },
  '90037': { city: 'Los Angeles', state: 'CA' },
  '90038': { city: 'Los Angeles', state: 'CA' },
  '90039': { city: 'Los Angeles', state: 'CA' },
  '90040': { city: 'Los Angeles', state: 'CA' },
  '90041': { city: 'Los Angeles', state: 'CA' },
  '90042': { city: 'Los Angeles', state: 'CA' },
  '90043': { city: 'Los Angeles', state: 'CA' },
  '90044': { city: 'Los Angeles', state: 'CA' },
  '90045': { city: 'Los Angeles', state: 'CA' },
  '90046': { city: 'Los Angeles', state: 'CA' },
  '90047': { city: 'Los Angeles', state: 'CA' },
  '90048': { city: 'Los Angeles', state: 'CA' },
  '90049': { city: 'Los Angeles', state: 'CA' },
  '90056': { city: 'Los Angeles', state: 'CA' },
  '90057': { city: 'Los Angeles', state: 'CA' },
  '90058': { city: 'Los Angeles', state: 'CA' },
  '90059': { city: 'Los Angeles', state: 'CA' },
  '90060': { city: 'Los Angeles', state: 'CA' },
  '90061': { city: 'Los Angeles', state: 'CA' },
  '90062': { city: 'Los Angeles', state: 'CA' },
  '90063': { city: 'Los Angeles', state: 'CA' },
  '90064': { city: 'Los Angeles', state: 'CA' },
  '90065': { city: 'Los Angeles', state: 'CA' },
  '90066': { city: 'Los Angeles', state: 'CA' },
  '90067': { city: 'Los Angeles', state: 'CA' },
  '90068': { city: 'Los Angeles', state: 'CA' },
  '90069': { city: 'Los Angeles', state: 'CA' },
  '90070': { city: 'Los Angeles', state: 'CA' },
  
  // San Francisco Bay Area
  '94102': { city: 'San Francisco', state: 'CA' },
  '94103': { city: 'San Francisco', state: 'CA' },
  '94104': { city: 'San Francisco', state: 'CA' },
  '94105': { city: 'San Francisco', state: 'CA' },
  '94107': { city: 'San Francisco', state: 'CA' },
  '94108': { city: 'San Francisco', state: 'CA' },
  '94109': { city: 'San Francisco', state: 'CA' },
  '94110': { city: 'San Francisco', state: 'CA' },
  '94111': { city: 'San Francisco', state: 'CA' },
  '94112': { city: 'San Francisco', state: 'CA' },
  '94114': { city: 'San Francisco', state: 'CA' },
  '94115': { city: 'San Francisco', state: 'CA' },
  '94116': { city: 'San Francisco', state: 'CA' },
  '94117': { city: 'San Francisco', state: 'CA' },
  '94118': { city: 'San Francisco', state: 'CA' },
  '94121': { city: 'San Francisco', state: 'CA' },
  '94122': { city: 'San Francisco', state: 'CA' },
  '94123': { city: 'San Francisco', state: 'CA' },
  '94124': { city: 'San Francisco', state: 'CA' },
  '94127': { city: 'San Francisco', state: 'CA' },
  '94131': { city: 'San Francisco', state: 'CA' },
  '94132': { city: 'San Francisco', state: 'CA' },
  '94133': { city: 'San Francisco', state: 'CA' },
  '94134': { city: 'San Francisco', state: 'CA' },
  
  // More Texas cities  
  '75231': { city: 'Dallas', state: 'TX' },
  '75232': { city: 'Dallas', state: 'TX' },
  '75233': { city: 'Dallas', state: 'TX' },
  '75234': { city: 'Dallas', state: 'TX' },
  '75235': { city: 'Dallas', state: 'TX' },
  '75236': { city: 'Dallas', state: 'TX' },
  '75237': { city: 'Dallas', state: 'TX' },
  '75238': { city: 'Dallas', state: 'TX' },
  '75240': { city: 'Dallas', state: 'TX' },
  '75241': { city: 'Dallas', state: 'TX' },
  '75242': { city: 'Dallas', state: 'TX' },
  '75243': { city: 'Dallas', state: 'TX' },
  '75244': { city: 'Dallas', state: 'TX' },
  '75246': { city: 'Dallas', state: 'TX' },
  '75247': { city: 'Dallas', state: 'TX' },
  '75248': { city: 'Dallas', state: 'TX' },
  '75249': { city: 'Dallas', state: 'TX' },
  '75250': { city: 'Dallas', state: 'TX' },
  
  // Austin
  '78701': { city: 'Austin', state: 'TX' },
  '78702': { city: 'Austin', state: 'TX' },
  '78703': { city: 'Austin', state: 'TX' },
  '78704': { city: 'Austin', state: 'TX' },
  '78705': { city: 'Austin', state: 'TX' },
  '78712': { city: 'Austin', state: 'TX' },
  '78717': { city: 'Austin', state: 'TX' },
  '78719': { city: 'Austin', state: 'TX' },
  '78721': { city: 'Austin', state: 'TX' },
  '78722': { city: 'Austin', state: 'TX' },
  '78723': { city: 'Austin', state: 'TX' },
  '78724': { city: 'Austin', state: 'TX' },
  '78725': { city: 'Austin', state: 'TX' },
  '78726': { city: 'Austin', state: 'TX' },
  '78727': { city: 'Austin', state: 'TX' },
  '78728': { city: 'Austin', state: 'TX' },
  '78729': { city: 'Austin', state: 'TX' },
  '78730': { city: 'Austin', state: 'TX' },
  '78731': { city: 'Austin', state: 'TX' },
  '78732': { city: 'Austin', state: 'TX' },
  '78733': { city: 'Austin', state: 'TX' },
  '78734': { city: 'Austin', state: 'TX' },
  '78735': { city: 'Austin', state: 'TX' },
  '78736': { city: 'Austin', state: 'TX' },
  '78737': { city: 'Austin', state: 'TX' },
  '78738': { city: 'Austin', state: 'TX' },
  '78739': { city: 'Austin', state: 'TX' },
  '78741': { city: 'Austin', state: 'TX' },
  '78742': { city: 'Austin', state: 'TX' },
  '78744': { city: 'Austin', state: 'TX' },
  '78745': { city: 'Austin', state: 'TX' },
  '78746': { city: 'Austin', state: 'TX' },
  '78747': { city: 'Austin', state: 'TX' },
  '78748': { city: 'Austin', state: 'TX' },
  '78749': { city: 'Austin', state: 'TX' },
  '78750': { city: 'Austin', state: 'TX' },
  '78751': { city: 'Austin', state: 'TX' },
  '78752': { city: 'Austin', state: 'TX' },
  '78753': { city: 'Austin', state: 'TX' },
  '78754': { city: 'Austin', state: 'TX' },
  '78756': { city: 'Austin', state: 'TX' },
  '78757': { city: 'Austin', state: 'TX' },
  '78758': { city: 'Austin', state: 'TX' },
  '78759': { city: 'Austin', state: 'TX' },
  
  // More Florida cities
  '33101': { city: 'Miami', state: 'FL' },
  '33102': { city: 'Miami', state: 'FL' },
  '33109': { city: 'Miami', state: 'FL' },
  '33111': { city: 'Miami', state: 'FL' },
  '33112': { city: 'Miami', state: 'FL' },
  '33114': { city: 'Miami', state: 'FL' },
  '33116': { city: 'Miami', state: 'FL' },
  '33122': { city: 'Miami', state: 'FL' },
  '33124': { city: 'Miami', state: 'FL' },
  '33125': { city: 'Miami', state: 'FL' },
  '33126': { city: 'Miami', state: 'FL' },
  '33127': { city: 'Miami', state: 'FL' },
  '33128': { city: 'Miami', state: 'FL' },
  '33129': { city: 'Miami', state: 'FL' },
  '33130': { city: 'Miami', state: 'FL' },
  '33131': { city: 'Miami', state: 'FL' },
  '33132': { city: 'Miami', state: 'FL' },
  '33133': { city: 'Miami', state: 'FL' },
  '33134': { city: 'Miami', state: 'FL' },
  '33135': { city: 'Miami', state: 'FL' },
  '33136': { city: 'Miami', state: 'FL' },
  '33137': { city: 'Miami', state: 'FL' },
  '33138': { city: 'Miami', state: 'FL' },
  '33139': { city: 'Miami', state: 'FL' },
  '33140': { city: 'Miami', state: 'FL' },
  '33141': { city: 'Miami', state: 'FL' },
  '33142': { city: 'Miami', state: 'FL' },
  '33143': { city: 'Miami', state: 'FL' },
  '33144': { city: 'Miami', state: 'FL' },
  '33145': { city: 'Miami', state: 'FL' },
  '33146': { city: 'Miami', state: 'FL' },
  '33147': { city: 'Miami', state: 'FL' },
  '33150': { city: 'Miami', state: 'FL' },
  '33151': { city: 'Miami', state: 'FL' },
  '33152': { city: 'Miami', state: 'FL' },
  '33153': { city: 'Miami', state: 'FL' },
  '33154': { city: 'Miami', state: 'FL' },
  '33155': { city: 'Miami', state: 'FL' },
  '33156': { city: 'Miami', state: 'FL' },
  '33157': { city: 'Miami', state: 'FL' },
  '33158': { city: 'Miami', state: 'FL' },
  '33160': { city: 'Miami', state: 'FL' },
  '33161': { city: 'Miami', state: 'FL' },
  '33162': { city: 'Miami', state: 'FL' },
  '33163': { city: 'Miami', state: 'FL' },
  '33164': { city: 'Miami', state: 'FL' },
  '33165': { city: 'Miami', state: 'FL' },
  '33166': { city: 'Miami', state: 'FL' },
  '33167': { city: 'Miami', state: 'FL' },
  '33168': { city: 'Miami', state: 'FL' },
  '33169': { city: 'Miami', state: 'FL' },
  '33170': { city: 'Miami', state: 'FL' },
  '33172': { city: 'Miami', state: 'FL' },
  '33173': { city: 'Miami', state: 'FL' },
  '33174': { city: 'Miami', state: 'FL' },
  '33175': { city: 'Miami', state: 'FL' },
  '33176': { city: 'Miami', state: 'FL' },
  '33177': { city: 'Miami', state: 'FL' },
  '33178': { city: 'Miami', state: 'FL' },
  '33179': { city: 'Miami', state: 'FL' },
  '33180': { city: 'Miami', state: 'FL' },
  '33181': { city: 'Miami', state: 'FL' },
  '33182': { city: 'Miami', state: 'FL' },
  '33183': { city: 'Miami', state: 'FL' },
  '33184': { city: 'Miami', state: 'FL' },
  '33185': { city: 'Miami', state: 'FL' },
  '33186': { city: 'Miami', state: 'FL' },
  '33187': { city: 'Miami', state: 'FL' },
  '33188': { city: 'Miami', state: 'FL' },
  '33189': { city: 'Miami', state: 'FL' },
  '33190': { city: 'Miami', state: 'FL' },
  '33193': { city: 'Miami', state: 'FL' },
  '33194': { city: 'Miami', state: 'FL' },
  '33195': { city: 'Miami', state: 'FL' },
  '33196': { city: 'Miami', state: 'FL' },
  '33197': { city: 'Miami', state: 'FL' },
  '33199': { city: 'Miami', state: 'FL' },
  
  // Seattle
  '98101': { city: 'Seattle', state: 'WA' },
  '98102': { city: 'Seattle', state: 'WA' },
  '98103': { city: 'Seattle', state: 'WA' },
  '98104': { city: 'Seattle', state: 'WA' },
  '98105': { city: 'Seattle', state: 'WA' },
  '98106': { city: 'Seattle', state: 'WA' },
  '98107': { city: 'Seattle', state: 'WA' },
  '98108': { city: 'Seattle', state: 'WA' },
  '98109': { city: 'Seattle', state: 'WA' },
  '98110': { city: 'Seattle', state: 'WA' },
  '98111': { city: 'Seattle', state: 'WA' },
  '98112': { city: 'Seattle', state: 'WA' },
  '98113': { city: 'Seattle', state: 'WA' },
  '98114': { city: 'Seattle', state: 'WA' },
  '98115': { city: 'Seattle', state: 'WA' },
  '98116': { city: 'Seattle', state: 'WA' },
  '98117': { city: 'Seattle', state: 'WA' },
  '98118': { city: 'Seattle', state: 'WA' },
  '98119': { city: 'Seattle', state: 'WA' },
  '98121': { city: 'Seattle', state: 'WA' },
  '98122': { city: 'Seattle', state: 'WA' },
  '98125': { city: 'Seattle', state: 'WA' },
  '98126': { city: 'Seattle', state: 'WA' },
  '98133': { city: 'Seattle', state: 'WA' },
  '98134': { city: 'Seattle', state: 'WA' },
  '98136': { city: 'Seattle', state: 'WA' },
  '98144': { city: 'Seattle', state: 'WA' },
  '98146': { city: 'Seattle', state: 'WA' },
  '98148': { city: 'Seattle', state: 'WA' },
  '98154': { city: 'Seattle', state: 'WA' },
  '98155': { city: 'Seattle', state: 'WA' },
  '98158': { city: 'Seattle', state: 'WA' },
  '98160': { city: 'Seattle', state: 'WA' },
  '98161': { city: 'Seattle', state: 'WA' },
  '98164': { city: 'Seattle', state: 'WA' },
  '98165': { city: 'Seattle', state: 'WA' },
  '98166': { city: 'Seattle', state: 'WA' },
  '98168': { city: 'Seattle', state: 'WA' },
  '98170': { city: 'Seattle', state: 'WA' },
  '98174': { city: 'Seattle', state: 'WA' },
  '98177': { city: 'Seattle', state: 'WA' },
  '98178': { city: 'Seattle', state: 'WA' },
  '98188': { city: 'Seattle', state: 'WA' },
  '98195': { city: 'Seattle', state: 'WA' },
  '98199': { city: 'Seattle', state: 'WA' },
  
  // Denver
  '80201': { city: 'Denver', state: 'CO' },
  '80202': { city: 'Denver', state: 'CO' },
  '80203': { city: 'Denver', state: 'CO' },
  '80204': { city: 'Denver', state: 'CO' },
  '80205': { city: 'Denver', state: 'CO' },
  '80206': { city: 'Denver', state: 'CO' },
  '80207': { city: 'Denver', state: 'CO' },
  '80208': { city: 'Denver', state: 'CO' },
  '80209': { city: 'Denver', state: 'CO' },
  '80210': { city: 'Denver', state: 'CO' },
  '80211': { city: 'Denver', state: 'CO' },
  '80212': { city: 'Denver', state: 'CO' },
  '80214': { city: 'Denver', state: 'CO' },
  '80215': { city: 'Denver', state: 'CO' },
  '80216': { city: 'Denver', state: 'CO' },
  '80218': { city: 'Denver', state: 'CO' },
  '80219': { city: 'Denver', state: 'CO' },
  '80220': { city: 'Denver', state: 'CO' },
  '80221': { city: 'Denver', state: 'CO' },
  '80222': { city: 'Denver', state: 'CO' },
  '80223': { city: 'Denver', state: 'CO' },
  '80224': { city: 'Denver', state: 'CO' },
  '80226': { city: 'Denver', state: 'CO' },
  '80227': { city: 'Denver', state: 'CO' },
  '80228': { city: 'Denver', state: 'CO' },
  '80230': { city: 'Denver', state: 'CO' },
  '80231': { city: 'Denver', state: 'CO' },
  '80232': { city: 'Denver', state: 'CO' },
  '80235': { city: 'Denver', state: 'CO' },
  '80236': { city: 'Denver', state: 'CO' },
  '80237': { city: 'Denver', state: 'CO' },
  '80238': { city: 'Denver', state: 'CO' },
  '80239': { city: 'Denver', state: 'CO' },
  '80246': { city: 'Denver', state: 'CO' },
  '80247': { city: 'Denver', state: 'CO' },
  '80249': { city: 'Denver', state: 'CO' },
  '80264': { city: 'Denver', state: 'CO' },
  '80290': { city: 'Denver', state: 'CO' },
  '80293': { city: 'Denver', state: 'CO' },
  // Los Angeles
  '90210': { city: 'Beverly Hills', state: 'CA' },
}

/**
 * Converts a zip code to city and state using API with caching
 * @param zipCode - 5-digit US zip code
 * @returns Promise<LocationInfo | null>
 */
export async function getLocationFromZipCode(zipCode: string): Promise<LocationInfo | null> {
  if (!zipCode || zipCode.length !== 5) {
    return null
  }
  
  // Check cache first
  if (locationCache.has(zipCode)) {
    return locationCache.get(zipCode) || null
  }
  
  // Try API first
  const apiResult = await fetchLocationFromAPI(zipCode)
  if (apiResult) {
    locationCache.set(zipCode, apiResult)
    return apiResult
  }
  
  // Fall back to local lookup
  const fallbackResult = FALLBACK_ZIP_TO_LOCATION[zipCode] || null
  locationCache.set(zipCode, fallbackResult)
  return fallbackResult
}

/**
 * Synchronous version using fallback data only
 * @param zipCode - 5-digit US zip code
 * @returns LocationInfo object with city and state, or null if not found
 */
export function getLocationFromZipCodeSync(zipCode: string): LocationInfo | null {
  if (!zipCode || zipCode.length !== 5) {
    return null
  }
  
  // Check cache first
  if (locationCache.has(zipCode)) {
    return locationCache.get(zipCode) || null
  }
  
  // Use fallback data
  return FALLBACK_ZIP_TO_LOCATION[zipCode] || null
}

/**
 * Formats location for display - tries cached/fallback lookup first, then zip code
 * @param zipCode - 5-digit US zip code
 * @returns Formatted location string (e.g., "Los Angeles, CA" or "12345")
 */
export function formatLocationDisplay(zipCode: string): string {
  if (!zipCode) return ''
  
  // Try synchronous lookup first (cache + fallback)
  const location = getLocationFromZipCodeSync(zipCode)
  if (location) {
    return `${location.city}, ${location.state}`
  }
  
  // Fallback to zip code if not found
  return zipCode
}

/**
 * Async version that tries API lookup then caches result
 * @param zipCode - 5-digit US zip code
 * @returns Promise<string> - Formatted location string
 */
export async function formatLocationDisplayAsync(zipCode: string): Promise<string> {
  if (!zipCode) return ''
  
  const location = await getLocationFromZipCode(zipCode)
  if (location) {
    return `${location.city}, ${location.state}`
  }
  
  return zipCode
}